version: '3'

services:
  file-storage:
    image: file_storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - R2DBC_URL=
      - R2DBC_USER=test
      - R2DBC_PASSWORD=test
      - DB_URL=
      - DB_USER=test
      - DB_PASSWORD=test
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_REGION=ru-central1
      - S3_URL=https://storage.yandexcloud.net
      - S3_BUCKET=files-strorage-repository
      - JWT_SECRET=
      - JWT_SECRET_ENCODER=FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      - ITERATION_ENCODER=64
      - KEYLENGTH_ENCODER=256
      - EXPIRATION=3600
      - ISSUER=Maxim
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql

