version: '3'

services:
  file-storage:
    image: file_storage
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - R2DBC_URL=r2dbc:mysql://mysql_db/rest
      - R2DBC_USER=test
      - R2DBC_PASSWORD=test
      - DB_URL=jdbc:mysql://mysql_db:3306/rest
      - DB_USER=test
      - DB_PASSWORD=test
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_REGION=ru-central1
      - S3_URL=https://storage.yandexcloud.net
      - S3_BUCKET=files-strorage-repository
      - JWT_SECRET=5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
      - JWT_SECRET_ENCODER=FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      - ITERATION_ENCODER=64
      - KEYLENGTH_ENCODER=256
      - EXPIRATION=3600
      - ISSUER=Maxim
    depends_on:
        - mysql_db
  mysql_db:
    image: mysql:latest
    ports:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
