server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/rest
    username: root
    password: root

s3:
  urlStorage: https://storage.yandexcloud.net
  region: ru-central1
  bucket: files-strorage-repository
  ACCESS_KEY:
  SECRET_KEY:

jwt:
  secret_encoder: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
  iteration_encoder: 64
  keylength_encoder: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: maxim

