server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/rest
    username: root
    password: root
#  main:
#    allow-bean-definition-overriding=true:

#  flyway:
#    url: jdbc:postgresql://localhost:5432/
#    locations: classpath:db/migration
#    user: ${spring.r2dbc.username}
#    password: ${spring.r2dbc.password}

jwt:
  issuer: maxim
  lifetime: 10m
  password:
    encoder:
      secret:
      iteration: 64
      keylength: 256

  secret:
  expiration: 3600

