server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USER}
    password: ${R2DBC_PASSWORD}
  flyway:
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/rest
    schemas: rest
    defaultSchema: rest
    user: root
    password: Addy@789**$
    baseline-on-migrate: true

s3:
  urlStorage: ${S3_URL}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}
  ACCESS_KEY: ${S3_ACCESS_KEY}
  SECRET_KEY: ${S3_SECRET_KEY}

jwt:
  secret_encoder: ${JWT_SECRET_ENCODER}
  iteration_encoder: ${ITERATION_ENCODER}
  keylength_encoder: ${KEYLENGTH_ENCODER}
  secret: ${JWT_SECRET}
  expiration: ${EXPIRATION}
  issuer: ${ISSUER}


